const world = new World();
const player = world.addPlayer(myId);
world.addBee(player, 1);
world.addBee(player, 2);
world.addBee(player, 3);
world.addBee(player, 4);
world.addBee(player, 5);
world.addBee(player, 6);
world.loop();
world.checkFightLoop();
